name: MLOps Pipeline

on:
  workflow_dispatch:
    inputs:
      run_all: 
        description: 'Run the entire MLOps pipeline'
        required: false
        default: 'true'
      run_data_processing:
        description: 'Run data processing step'
        required: false
        default: 'false'
      run_model_training:
        description: 'Run model training step'
        required: false
        default: 'false'
      run_build_and_publish:
        description: 'Run build and publish step'
        required: false
        default: 'false'
  release:
    types: [created]
    branches: [ main]
    tags: [ 'v*.*.*' ]

jobs:
  data_processing: 
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.11.9"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Process data 
      run: |
        python src/data/run_processing.py \
        --input data/raw/house_data.csv \
        --output data/processed/cleaned_house_data.csv

    - name: Engineer features 
      run: |
        python src/features/engineer.py \
        --input data/processed/cleaned_house_data.csv \
        --output data/processed/featured_house_data.csv \
        --preprocessor models/trained/preprocessor.pkl

    - name: Upload Processed Data
      uses: actions/upload-artifact@v4
      with:
        name: processed-data
        path: data/processed/featured_house_data.csv

    - name: Upload Preprocessor
      uses: actions/upload-artifact@v4
      with:
        name: preprocessor
        path: models/trained/preprocessor.pkl

  model_training:
    needs: data_processing
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.11.9"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download Processed Data
      uses: actions/download-artifact@v4
      with:
        name: processed-data
        path: data/processed/

    - name: Setup MLflow Server 
      run: |
        docker pull ghcr.io/mlflow/mlflow:latest
        docker run -d -p 5555:5000 --name MLflow-Server ghcr.io/mlflow/mlflow:latest mlflow server --host 0.0.0.0 --backend-store-uri sqlite:///mlflow.db 

    - name: wait for MLflow Server to be ready
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:5555/ > /dev/null; then
            echo "MLflow Server is ready!"
            break
          else
            echo "Waiting for MLflow Server to be ready..."
            sleep 5
          fi
        done

    - name: Train Model
      run: |
        python src/models/train_model.py \
        --config configs/model_config.yaml \
        --data data/processed/featured_house_data.csv \
        --models-dir models \
        --mlflow-tracking-uri http://localhost:5555
    
    - name: Upload Trained Model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/ 

    - name: Cleanup MLflow Server
      run: |
        docker stop MLflow-Server
        docker rm MLflow-Server
    
  build_and_publish:
    needs: model_training
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Trained Model
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: models/

      - name: download preprocessor
        uses: actions/download-artifact@v4
        with:
          name: preprocessor
          path: models/trained/ 
      
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: build and test docker image
        run: |
          COMMIT_HASH=$(echo ${{ github.sha }} | cut -c1-7)
          # Define the image name once to avoid typos
          FULL_IMAGE_NAME=docker.io/${{ vars.DOCKER_USERNAME }}/fastapi:${COMMIT_HASH}
          
          # Build using the defined name
          docker build -t ${FULL_IMAGE_NAME} -f Dockerfile .
          
          # Run using the EXACT SAME name
          docker run -d -p 8000:8000 --name test-api ${FULL_IMAGE_NAME}
          
          # Health check
          for i in {1..10}; do
            curl -f http://localhost:8000/health && break || sleep 5; 
          done 
          docker logs test-api

      - name: clean up test container
        run: |
          docker stop test-api || true
          docker rm test-api || true

      - name: login to Docker container registry
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: push docker image
        run: |
          COMMIT_HASH=$(echo ${{ github.sha }} | cut -c1-7)
          docker tag docker.io/${{ vars.DOCKER_USERNAME }}/fastapi:${COMMIT_HASH} docker.io/${{ vars.DOCKER_USERNAME }}/fastapi:latest
          docker push docker.io/${{ vars.DOCKER_USERNAME }}/fastapi:${COMMIT_HASH}
          docker push docker.io/${{ vars.DOCKER_USERNAME }}/fastapi:latest